FROM node:20-alpine3.18 AS base

ENV DIR /app
WORKDIR $DIR

FROM base AS dev

ENV NODE_ENV=development

COPY package*.json .

RUN npm ci

COPY .npmignore .
COPY .npmrc .
COPY tsconfig*.json .
COPY nest-cli.json .
COPY libs libs
COPY src src

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:dev"]