name: Release

on:
  push:
    branches:
      - main
      - beta
      - alpha
permissions:
  contents: read # for checkout
jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      
      - name: audit provenance
        run: npm audit signatures

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
      
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          REGISTRY_URL: ${{ vars.REGISTRY_URL }}
          REPOSITORY_URL: ${{ vars.REPOSITORY_URL }}
          REGISTRY_SCOPE: ${{ vars.REGISTRY_SCOPE }}

      