name: Release package

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: '*'

jobs:
  build:
    permissions:
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Verify provenance and registry signatures
        run: npm audit signatures
      - run: npm test

  publish:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/HEAD/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: ${{ secrets.GH_REGISTRY }}
      - run: npm ci
      - run: npm run build
      - name: Release semantic-release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
